import { buildShowtimesForMovie } from "@/lib/showtime-schedule";
import type { Cinema, CinemaBrand } from "@/types/domain";
import type { ShowtimeRepository } from "@/types/repositories";

const brands: readonly CinemaBrand[] = [
  {
    id: "cgv",
    name: "CGV Cinemas",
    shortName: "CGV",
    logoPath: "/assets/logo/cgv-logo.png",
  },
  {
    id: "lotte",
    name: "Lotte Cinema",
    shortName: "Lotte",
    logoPath: "/assets/logo/lotte-logo.png",
  },
  {
    id: "galaxy",
    name: "Galaxy Cinema",
    shortName: "Galaxy",
    logoPath: "/assets/logo/galaxy-logo.png",
  },
  {
    id: "bhd",
    name: "BHD Star Cineplex",
    shortName: "BHD Star",
    logoPath: "/assets/logo/bhd-logo.png",
  },
  {
    id: "beta",
    name: "Beta Cinemas",
    shortName: "Beta",
    logoPath: "/assets/logo/beta-logo.webp",
  },
  {
    id: "cinestar",
    name: "Cinestar",
    shortName: "Cinestar",
    logoPath: "/assets/logo/cinestar-logo.png",
  },
  {
    id: "megags",
    name: "Mega GS Cinemas",
    shortName: "Mega GS",
    logoPath: "/assets/logo/megags-logo.webp",
  },
  {
    id: "dcine",
    name: "DCINE",
    shortName: "DCINE",
    logoPath: "/assets/logo/dcine-logo.png",
  },
];

const cinemas: readonly Cinema[] = [
  {
    id: "cgv-landmark-81",
    brandId: "cgv",
    name: "CGV Landmark 81",
    areaName: "Bình Thạnh",
    cityName: "TP. Hồ Chí Minh",
    address: "772 Điện Biên Phủ, Bình Thạnh, TP. Hồ Chí Minh",
    features: ["IMAX", "4DX", "Dolby Atmos"],
    latitude: 10.7947,
    longitude: 106.7218,
  },
  {
    id: "cgv-vincom-dong-khoi",
    brandId: "cgv",
    name: "CGV Vincom Đồng Khởi",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "72 Lê Thánh Tôn, Quận 1, TP. Hồ Chí Minh",
    features: ["IMAX", "Dolby Atmos", "Sweetbox"],
    latitude: 10.7779,
    longitude: 106.7017,
  },
  {
    id: "lotte-nam-sai-gon",
    brandId: "lotte",
    name: "Lotte Cinema Nam Sài Gòn",
    areaName: "Quận 7",
    cityName: "TP. Hồ Chí Minh",
    address: "469 Nguyễn Hữu Thọ, Quận 7, TP. Hồ Chí Minh",
    features: ["Super Plex G", "Dolby Atmos", "Couple Seats"],
    latitude: 10.7295,
    longitude: 106.7186,
  },
  {
    id: "lotte-go-vap",
    brandId: "lotte",
    name: "Lotte Cinema Gò Vấp",
    areaName: "Gò Vấp",
    cityName: "TP. Hồ Chí Minh",
    address: "242 Nguyễn Văn Lượng, Gò Vấp, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Couple Seats"],
    latitude: 10.838,
    longitude: 106.665,
  },
  {
    id: "galaxy-nguyen-du",
    brandId: "galaxy",
    name: "Galaxy Nguyễn Du",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "116 Nguyễn Du, Quận 1, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Premium Lounge"],
    latitude: 10.7739,
    longitude: 106.695,
  },
  {
    id: "galaxy-tan-binh",
    brandId: "galaxy",
    name: "Galaxy Tân Bình",
    areaName: "Tân Bình",
    cityName: "TP. Hồ Chí Minh",
    address: "246 Nguyễn Hồng Đào, Tân Bình, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Family Hall"],
    latitude: 10.801,
    longitude: 106.652,
  },
  {
    id: "bhd-bitexco",
    brandId: "bhd",
    name: "BHD Star Bitexco",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "2 Hải Triều, Quận 1, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Premium Lounge", "Couple Seats"],
    latitude: 10.7717,
    longitude: 106.7043,
  },
  {
    id: "bhd-pham-hung",
    brandId: "bhd",
    name: "BHD Star Phạm Hùng",
    areaName: "Bình Chánh",
    cityName: "TP. Hồ Chí Minh",
    address: "1362 Phạm Hùng, Bình Chánh, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Family Hall"],
    latitude: 10.7405,
    longitude: 106.669,
  },
  {
    id: "beta-tran-quang-khai",
    brandId: "beta",
    name: "Beta Trần Quang Khải",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "18B Trần Quang Khải, Quận 1, TP. Hồ Chí Minh",
    features: ["Giá rẻ", "Couple Seats"],
    latitude: 10.792,
    longitude: 106.69,
  },
  {
    id: "beta-quang-trung",
    brandId: "beta",
    name: "Beta Quang Trung",
    areaName: "Gò Vấp",
    cityName: "TP. Hồ Chí Minh",
    address: "645 Quang Trung, Gò Vấp, TP. Hồ Chí Minh",
    features: ["Giá rẻ", "Family Hall"],
    latitude: 10.842,
    longitude: 106.639,
  },
  {
    id: "cinestar-quoc-thanh",
    brandId: "cinestar",
    name: "Cinestar Quốc Thanh",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "271 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
    features: ["Giá rẻ", "Dolby Atmos", "Couple Seats"],
    latitude: 10.7645,
    longitude: 106.6845,
  },
  {
    id: "cinestar-hai-ba-trung",
    brandId: "cinestar",
    name: "Cinestar Hai Bà Trưng",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "135 Hai Bà Trưng, Quận 1, TP. Hồ Chí Minh",
    features: ["Giá rẻ", "Family Hall"],
    latitude: 10.7855,
    longitude: 106.6975,
  },
  {
    id: "megags-cao-thang",
    brandId: "megags",
    name: "Mega GS Cao Thắng",
    areaName: "Quận 3",
    cityName: "TP. Hồ Chí Minh",
    address: "19 Cao Thắng, Quận 3, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Couple Seats"],
    latitude: 10.769,
    longitude: 106.681,
  },
  {
    id: "megags-ly-chinh-thang",
    brandId: "megags",
    name: "Mega GS Lý Chính Thắng",
    areaName: "Quận 3",
    cityName: "TP. Hồ Chí Minh",
    address: "212 Lý Chính Thắng, Quận 3, TP. Hồ Chí Minh",
    features: ["Dolby Atmos", "Premium Lounge"],
    latitude: 10.786,
    longitude: 106.684,
  },
  {
    id: "dcine-ben-thanh",
    brandId: "dcine",
    name: "DCINE Bến Thành",
    areaName: "Quận 1",
    cityName: "TP. Hồ Chí Minh",
    address: "6 Mạc Đĩnh Chi, Quận 1, TP. Hồ Chí Minh",
    features: ["Boutique", "Couple Seats"],
    latitude: 10.7725,
    longitude: 106.698,
  },
  {
    id: "dcine-thao-dien",
    brandId: "dcine",
    name: "DCINE Thảo Điền",
    areaName: "TP. Thủ Đức",
    cityName: "TP. Hồ Chí Minh",
    address: "12 Quốc Hương, TP. Thủ Đức, TP. Hồ Chí Minh",
    features: ["Boutique", "Premium Lounge"],
    latitude: 10.8035,
    longitude: 106.7345,
  },
  {
    id: "cgv-vincom-ba-trieu",
    brandId: "cgv",
    name: "CGV Vincom Bà Triệu",
    areaName: "Hai Bà Trưng",
    cityName: "Hà Nội",
    address: "191 Bà Triệu, Hai Bà Trưng, Hà Nội",
    features: ["IMAX", "Dolby Atmos", "Sweetbox"],
    latitude: 21.01,
    longitude: 105.849,
  },
  {
    id: "cgv-aeon-long-bien",
    brandId: "cgv",
    name: "CGV Aeon Long Biên",
    areaName: "Long Biên",
    cityName: "Hà Nội",
    address: "27 Cổ Linh, Long Biên, Hà Nội",
    features: ["4DX", "Dolby Atmos"],
    latitude: 21.028,
    longitude: 105.899,
  },
  {
    id: "lotte-landmark-72",
    brandId: "lotte",
    name: "Lotte Cinema Landmark 72",
    areaName: "Nam Từ Liêm",
    cityName: "Hà Nội",
    address: "Phạm Hùng, Nam Từ Liêm, Hà Nội",
    features: ["Super Plex G", "Dolby Atmos", "Couple Seats"],
    latitude: 21.0175,
    longitude: 105.783,
  },
  {
    id: "galaxy-mipec-long-bien",
    brandId: "galaxy",
    name: "Galaxy Mipec Long Biên",
    areaName: "Long Biên",
    cityName: "Hà Nội",
    address: "2 Long Biên 2, Long Biên, Hà Nội",
    features: ["Dolby Atmos", "Premium Lounge"],
    latitude: 21.044,
    longitude: 105.872,
  },
  {
    id: "bhd-pham-ngoc-thach",
    brandId: "bhd",
    name: "BHD Star Phạm Ngọc Thạch",
    areaName: "Đống Đa",
    cityName: "Hà Nội",
    address: "2 Phạm Ngọc Thạch, Đống Đa, Hà Nội",
    features: ["Dolby Atmos", "Couple Seats"],
    latitude: 21.0075,
    longitude: 105.833,
  },
  {
    id: "beta-my-dinh",
    brandId: "beta",
    name: "Beta Mỹ Đình",
    areaName: "Nam Từ Liêm",
    cityName: "Hà Nội",
    address: "Mỹ Đình, Nam Từ Liêm, Hà Nội",
    features: ["Giá rẻ", "Family Hall"],
    latitude: 21.029,
    longitude: 105.776,
  },
  {
    id: "cgv-vincom-da-nang",
    brandId: "cgv",
    name: "CGV Vincom Đà Nẵng",
    areaName: "Sơn Trà",
    cityName: "Đà Nẵng",
    address: "910A Ngô Quyền, Sơn Trà, Đà Nẵng",
    features: ["IMAX", "Dolby Atmos"],
    latitude: 16.062,
    longitude: 108.228,
  },
  {
    id: "lotte-da-nang",
    brandId: "lotte",
    name: "Lotte Cinema Đà Nẵng",
    areaName: "Hải Châu",
    cityName: "Đà Nẵng",
    address: "6 Nại Nam, Hải Châu, Đà Nẵng",
    features: ["Dolby Atmos", "Couple Seats"],
    latitude: 16.03,
    longitude: 108.223,
  },
  {
    id: "galaxy-da-nang",
    brandId: "galaxy",
    name: "Galaxy Đà Nẵng",
    areaName: "Thanh Khê",
    cityName: "Đà Nẵng",
    address: "278 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng",
    features: ["Dolby Atmos", "Premium Lounge"],
    latitude: 16.06,
    longitude: 108.21,
  },
  {
    id: "beta-da-nang",
    brandId: "beta",
    name: "Beta Đà Nẵng",
    areaName: "Liên Chiểu",
    cityName: "Đà Nẵng",
    address: "Hòa Khánh, Liên Chiểu, Đà Nẵng",
    features: ["Giá rẻ", "Family Hall"],
    latitude: 16.073,
    longitude: 108.15,
  },
];

export const mockShowtimeRepository: ShowtimeRepository = {
  async findBrands() {
    return brands;
  },

  async findCinemas() {
    return cinemas;
  },

  async findShowtimesByMovie(movieId) {
    return buildShowtimesForMovie(movieId, cinemas);
  },
};
