(function () {
  "use strict";

  const movies = [
    {
      id: "minions-monsters",
      title: "Minions & Monsters",
      displayTitle: "MINIONS & MONSTERS",
      tagline: "Từ một đội quân tí hon, đến một hành trình vĩ đại.",
      status: "now-showing",
      featured: true,
      premiere: true,
      rating: "P",
      score: "8.7",
      duration: 104,
      release: "01.07.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Animation", "Family", "Comedy"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một chuyến phiêu lưu hoạt hình đầy năng lượng đưa biệt đội tí hon đến với thử thách lớn nhất từ trước đến nay. Khi một thế lực bí ẩn xuất hiện, lòng can đảm và tinh thần đồng đội trở thành chìa khóa cho hành trình mới.",
      shortDescription: "Một đội quân tí hon đối mặt với cuộc phiêu lưu lớn nhất từ trước đến nay.",
      poster: "assets/media/posters/minions-monsters.webp",
      backdrop: "assets/media/backdrops/minions-monsters.webp",
      videoThumb: "assets/media/promos/minions-monsters-wide.webp",
      previewVideo: "assets/media/video/minions-monsters.webm",
      accent: "#ffcf35",
      formats: ["2D", "IMAX", "4DX"]
    },
    {
      id: "super-mario-galaxy",
      title: "The Super Mario Galaxy Movie",
      displayTitle: "THE SUPER MARIO GALAXY MOVIE",
      tagline: "Một chuyến phiêu lưu mới mở ra giữa các vì sao.",
      status: "now-showing",
      featured: true,
      premiere: false,
      rating: "K",
      score: "8.9",
      duration: 112,
      release: "01.04.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Animation", "Adventure", "Family"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một chuyến phiêu lưu xuyên thiên hà mở ra khi những người hùng quen thuộc bước vào thế giới mới giữa các vì sao. Họ phải vượt qua những vùng đất kỳ ảo và cùng nhau tìm đường trở về nhà.",
      shortDescription: "Một chuyến phiêu lưu mới mở ra giữa các vì sao và những thế giới kỳ ảo.",
      poster: "assets/media/posters/super-mario-galaxy.webp",
      backdrop: "assets/media/backdrops/super-mario-galaxy.webp",
      videoThumb: "assets/media/promos/super-mario-galaxy-wide.mp4",
      previewVideo: "assets/media/video/super-mario-galaxy-wide.webm",
      accent: "#66c8ff",
      formats: ["2D", "IMAX", "4DX"]
    },
    {
      id: "reminders-of-him",
      title: "Reminders of Him",
      displayTitle: "REMINDERS OF HIM",
      tagline: "Some memories ask for a second chance.",
      status: "now-showing",
      featured: false,
      premiere: false,
      rating: "T13",
      score: "8.4",
      duration: 118,
      release: "13.03.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Drama", "Romance"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một câu chuyện giàu cảm xúc về ký ức, lựa chọn và cơ hội làm lại từ đầu. Hành trình trở về buộc các nhân vật phải đối diện với những điều chưa thể khép lại trong quá khứ.",
      shortDescription: "Một hành trình trở về buộc con người phải đối diện với ký ức chưa khép lại.",
      poster: "assets/media/posters/reminders-of-him.webp",
      backdrop: "assets/media/backdrops/reminders-of-him.webp",
      previewVideo: "assets/media/video/reminders-of-him.webm",
      accent: "#f39b76",
      formats: ["2D", "Premium"]
    },
    {
      id: "you-me-tuscany",
      title: "You, Me and Tuscany",
      displayTitle: "YOU, ME AND TUSCANY",
      tagline: "Sometimes the detour becomes the destination.",
      status: "now-showing",
      featured: false,
      premiere: false,
      rating: "T13",
      score: "8.2",
      duration: 108,
      release: "10.04.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Romance", "Comedy", "Drama"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một kỳ nghỉ bất ngờ trở thành hành trình khám phá tình cảm và những lựa chọn mới. Giữa khung cảnh Tuscany, một chuyến đi ngoài kế hoạch có thể thay đổi mọi dự định ban đầu.",
      shortDescription: "Một chuyến đi ngoài kế hoạch mở ra những lựa chọn không ai dự đoán trước.",
      poster: "assets/media/posters/you-me-tuscany.webp",
      backdrop: "assets/media/backdrops/you-me-and-tuscany.webp",
      previewVideo: "assets/media/video/you-me-and-tuscany.webm",
      accent: "#f6c08b",
      formats: ["2D", "Premium"]
    },
    {
      id: "disclosure-day",
      title: "Disclosure Day",
      displayTitle: "DISCLOSURE DAY",
      tagline: "Chúng ta xứng đáng được biết sự thật.",
      status: "coming-soon",
      featured: true,
      premiere: true,
      rating: "T13",
      score: "Coming soon",
      duration: 126,
      release: "03.07.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Sci-Fi", "Thriller", "Drama"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một bí mật có quy mô toàn cầu chuẩn bị được hé lộ. Khi những tín hiệu bất thường xuất hiện đồng thời trên khắp thế giới, câu hỏi lớn nhất không còn là điều gì đang xảy ra mà là ai đã biết sự thật từ trước.",
      shortDescription: "Một tín hiệu bí ẩn đặt cả thế giới trước câu hỏi không thể trì hoãn.",
      poster: "assets/media/posters/disclosure-day.webp",
      backdrop: "assets/media/backdrops/disclosure-day.webp",
      videoThumb: "assets/media/promos/disclosure-day-wide.webm",
      previewVideo: "assets/media/video/disclosure-day.webm",
      accent: "#70e1ff",
      formats: ["2D", "IMAX"]
    },
    {
      id: "the-odyssey",
      title: "The Odyssey",
      displayTitle: "THE ODYSSEY",
      tagline: "Cái giá của sự vĩ đại.",
      status: "coming-soon",
      featured: true,
      premiere: false,
      rating: "T13",
      score: "Coming soon",
      duration: 152,
      release: "17.07.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Adventure", "Drama", "Fantasy"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một thiên sử thi điện ảnh về hành trình trở về, thử thách và ý chí sinh tồn. Trên con đường vượt biển đầy hiểm nguy, mỗi quyết định đều phải trả giá và mỗi chiến thắng đều để lại dấu ấn.",
      shortDescription: "Một cuộc viễn chinh khắc nghiệt đưa người anh hùng vượt qua giới hạn của chính mình.",
      poster: "assets/media/posters/the-odyssey.webp",
      backdrop: "assets/media/backdrops/the-odyssey.webp",
      videoThumb: "assets/media/promos/the-odyssey.mp4",
      previewVideo: "assets/media/video/the-odyssey.webm",
      accent: "#e59a5b",
      formats: ["2D", "IMAX"]
    },
    {
      id: "forgotten-island",
      title: "Forgotten Island",
      displayTitle: "FORGOTTEN ISLAND",
      tagline: "Có những nơi bị xóa sổ hoàn toàn là có lý do.",
      status: "coming-soon",
      featured: true,
      premiere: false,
      rating: "T16",
      score: "Coming soon",
      duration: 128,
      release: "25.09.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Adventure", "Thriller", "Mystery"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một hòn đảo biến mất khỏi bản đồ trở thành tâm điểm của chuyến thám hiểm không thể quay đầu. Càng tiến sâu, đoàn thám hiểm càng nhận ra có những nơi bị lãng quên vì một lý do đáng sợ.",
      shortDescription: "Một đoàn thám hiểm tìm đến hòn đảo bị xóa khỏi mọi bản đồ hiện đại.",
      poster: "assets/media/posters/forgotten-island.webp",
      backdrop: "assets/media/backdrops/forgotten-island.webp",
      previewVideo: "assets/media/video/forgotten-island.webm",
      accent: "#76bc9c",
      formats: ["2D", "IMAX"]
    },
    {
      id: "focker-in-law",
      title: "Focker-In-Law",
      displayTitle: "FOCKER-IN-LAW",
      tagline: "Family meetings are never simple.",
      status: "coming-soon",
      featured: false,
      premiere: false,
      rating: "T13",
      score: "Coming soon",
      duration: 114,
      release: "25.11.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Comedy", "Family"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một cuộc hội ngộ gia đình biến thành chuỗi tình huống khó lường. Những kế hoạch tưởng như đơn giản nhanh chóng vượt ngoài tầm kiểm soát khi mọi bí mật lần lượt được tiết lộ.",
      shortDescription: "Một cuộc gặp mặt gia đình nhanh chóng trở thành thử thách không ai chuẩn bị trước.",
      poster: "assets/media/posters/focker-in-law.webp",
      backdrop: "assets/media/backdrops/focker-in-law.webp",
      previewVideo: "assets/media/video/focker-in-law.webm",
      accent: "#ffbd70",
      formats: ["2D"]
    },
    {
      id: "one-night-only",
      title: "One Night Only",
      displayTitle: "ONE NIGHT ONLY",
      tagline: "One night can change every plan.",
      status: "coming-soon",
      featured: false,
      premiere: false,
      rating: "T16",
      score: "Coming soon",
      duration: 110,
      release: "07.08.2026",
      language: "English · Vietnamese subtitles",
      genre: ["Drama", "Thriller"],
      director: "CINEVERSE Featured Presentation",
      cast: ["Thông tin đang cập nhật"],
      description: "Một đêm duy nhất mở ra hàng loạt lựa chọn có thể thay đổi tương lai. Khi thời gian không còn đứng về phía họ, mỗi nhân vật buộc phải quyết định điều gì thực sự đáng để bảo vệ.",
      shortDescription: "Một đêm duy nhất buộc mọi nhân vật phải đưa ra lựa chọn quyết định.",
      poster: "assets/media/posters/one-night-only.webp",
      backdrop: "assets/media/posters/one-night-only.webp",
      previewVideo: "assets/media/video/one-night-only.webm",
      accent: "#f77b78",
      formats: ["2D"]
    },
    {
      id: "five-nights-at-freddys-2",
      title: "Five Nights at Freddy's 2",
      displayTitle: "FIVE NIGHTS AT FREDDY'S 2",
      tagline: "The night shift is not over.",
      status: "coming-soon",
      featured: false,
      premiere: false,
      rating: "T18",
      score: "Special event",
      duration: 112,
      release: "Sự kiện đặc biệt",
      language: "English · Vietnamese subtitles",
      genre: ["Horror", "Thriller"],
      director: "CINEVERSE Special Screening",
      cast: ["Thông tin đang cập nhật"],
      description: "Ca trực đêm tưởng như đã kết thúc lại mở ra một chương mới đáng sợ hơn. Những tín hiệu quen thuộc trở lại, kéo theo bí mật chưa từng được hé lộ trong bóng tối.",
      shortDescription: "Ca trực đêm trở lại với những dấu hiệu cho thấy mọi chuyện chưa kết thúc.",
      poster: "assets/media/posters/five-nights-at-freddys-2.webp",
      backdrop: "assets/media/backdrops/five-nights-at-freddys-2.webp",
      previewVideo: "assets/media/video/five-nights-at-freddys-2.webm",
      accent: "#e64949",
      formats: ["2D"]
    },
    {
      id: "wicked-for-good",
      title: "Wicked: For Good",
      displayTitle: "WICKED: FOR GOOD",
      tagline: "Every story leaves an echo.",
      status: "coming-soon",
      featured: false,
      premiere: false,
      rating: "T13",
      score: "Special event",
      duration: 138,
      release: "Sự kiện đặc biệt",
      language: "English · Vietnamese subtitles",
      genre: ["Fantasy", "Musical", "Drama"],
      director: "CINEVERSE Special Screening",
      cast: ["Thông tin đang cập nhật"],
      description: "Một chương mới của câu chuyện kỳ ảo mở ra với những lựa chọn khó khăn, tình bạn bị thử thách và những hệ quả còn vang vọng rất lâu sau khi sân khấu khép lại.",
      shortDescription: "Một chương mới của câu chuyện kỳ ảo được giới thiệu trong suất chiếu đặc biệt.",
      poster: "assets/media/posters/wicked-for-good.webp",
      backdrop: "assets/media/backdrops/wicked-for-good.webp",
      previewVideo: "assets/media/video/wicked-for-good-final-trailer.webm",
      accent: "#e991d8",
      formats: ["2D", "Premium"]
    },
    {
      id: "black-phone-2",
      title: "Black Phone 2",
      displayTitle: "BLACK PHONE 2",
      tagline: "Some calls should never be answered.",
      status: "coming-soon",
      featured: false,
      premiere: false,
      rating: "T18",
      score: "Special event",
      duration: 116,
      release: "Sự kiện đặc biệt",
      language: "English · Vietnamese subtitles",
      genre: ["Horror", "Mystery", "Thriller"],
      director: "CINEVERSE Special Screening",
      cast: ["Thông tin đang cập nhật"],
      description: "Một tín hiệu từ quá khứ khiến cuộc gọi tưởng đã kết thúc bắt đầu vang lên trở lại. Những bí ẩn mới xuất hiện, kéo người nghe vào hành trình không thể quay đầu.",
      shortDescription: "Một tín hiệu từ quá khứ khiến cuộc gọi tưởng đã kết thúc bắt đầu vang lên trở lại.",
      poster: "assets/media/posters/black-phone-2.webp",
      backdrop: "assets/media/backdrops/black-phone-2.jpg",
      previewVideo: "assets/media/video/black-phone-2.webm",
      accent: "#d97070",
      formats: ["2D"]
    }
  ];

  const cinemas = [
    {
      id: "landmark-81",
      name: "CINEVERSE Landmark 81",
      address: "208 Nguyễn Hữu Cảnh, Bình Thạnh, TP. Hồ Chí Minh",
      distance: "2.4 km",
      features: ["IMAX", "4DX", "Dolby Atmos"],
      halls: ["IMAX 01", "Hall 03", "Hall 05"]
    },
    {
      id: "vincom-center",
      name: "CINEVERSE Vincom Center",
      address: "72 Lê Thánh Tôn, Quận 1, TP. Hồ Chí Minh",
      distance: "3.1 km",
      features: ["ScreenX", "Dolby Atmos", "Premium Lounge"],
      halls: ["ScreenX 02", "Hall 06", "Hall 08"]
    },
    {
      id: "crescent-mall",
      name: "CINEVERSE Crescent Mall",
      address: "101 Tôn Dật Tiên, Quận 7, TP. Hồ Chí Minh",
      distance: "7.8 km",
      features: ["4DX", "Couple Seats", "Premium Lounge"],
      halls: ["4DX 01", "Hall 04", "Hall 07"]
    },
    {
      id: "aeon-tan-phu",
      name: "CINEVERSE AEON Tân Phú",
      address: "30 Bờ Bao Tân Thắng, Tân Phú, TP. Hồ Chí Minh",
      distance: "9.6 km",
      features: ["Dolby Atmos", "Family Hall", "Couple Seats"],
      halls: ["Hall 02", "Hall 05", "Hall 09"]
    }
  ];

  const combos = [
    {
      id: "classic-duo",
      name: "Classic Duo",
      description: "01 bắp rang bơ lớn + 02 nước ngọt vừa",
      price: 149000,
      image: "assets/combos/classic-duo.svg",
      badge: "Bán chạy"
    },
    {
      id: "galaxy-box",
      name: "Galaxy Box",
      description: "01 bắp rang bơ lớn + 01 nachos + 02 nước ngọt lớn",
      price: 219000,
      image: "assets/combos/galaxy-box.svg",
      badge: "Tiết kiệm 12%"
    },
    {
      id: "star-snack",
      name: "Star Snack",
      description: "01 hot dog + 01 nước ngọt vừa",
      price: 99000,
      image: "assets/combos/star-snack.svg",
      badge: "Đồ ăn nhẹ"
    },
    {
      id: "kids-orbit",
      name: "Kids Orbit",
      description: "01 bắp rang bơ nhỏ + 01 nước trái cây + 01 mô hình mini",
      price: 129000,
      image: "assets/combos/kids-orbit.svg",
      badge: "Dành cho bé"
    }
  ];

  const featuredVideos = [
    {
      id: "video-disclosure-day",
      movieId: "disclosure-day",
      title: "Disclosure Day — First Look",
      label: "Featured preview",
      duration: "02:18",
      image: "assets/media/promos/disclosure-day-wide.webp"
    },
    {
      id: "video-minions-monsters",
      movieId: "minions-monsters",
      title: "Minions & Monsters — Local Hero Video",
      label: "Official preview",
      duration: "00:28",
      image: "assets/media/promos/minions-monsters-wide.webp"
    },
    {
      id: "video-super-mario-galaxy",
      movieId: "super-mario-galaxy",
      title: "The Super Mario Galaxy Movie — preview",
      label: "Featured preview",
      duration: "01:42",
      image: "assets/media/promos/super-mario-galaxy-wide.webp"
    },
    {
      id: "video-the-odyssey",
      movieId: "the-odyssey",
      title: "The Odyssey — New Journey",
      label: "Featured preview",
      duration: "02:06",
      image: "assets/media/promos/the-odyssey-wide.webp"
    }
  ];

  const promos = [
    {
      id: "promo-wicked",
      title: "Wicked: For Good",
      label: "Nội dung nổi bật",
      copy: "Khám phá câu chuyện kỳ ảo qua những khung hình nổi bật.",
      image: "assets/media/promos/wicked-for-good.webp"
    },
    {
      id: "promo-fnaf",
      title: "Five Nights at Freddy's 2",
      label: "Suất chiếu sự kiện",
      copy: "Đón chờ suất chiếu sự kiện dành cho khán giả yêu thích thể loại kinh dị.",
      image: "assets/media/promos/five-nights-at-freddys-2.webp"
    },
    {
      id: "promo-ted",
      title: "Ted Season 2",
      label: "CINEVERSE Extras",
      copy: "Theo dõi nội dung nổi bật và những khoảnh khắc giải trí đáng nhớ.",
      image: "assets/media/promos/ted-season-2.webp"
    },
    {
      id: "promo-jurassic",
      title: "Jurassic x Xfinity",
      label: "Partner spotlight",
      copy: "Khám phá nội dung hợp tác đặc biệt trong hệ sinh thái CINEVERSE.",
      image: "assets/media/promos/jurassic-x-xfinity.webp"
    }
  ];

  window.CINEVERSE_DATA = {
    movies: movies,
    cinemas: cinemas,
    combos: combos,
    featuredVideos: featuredVideos,
    promos: promos,
    ticketPrices: {
      standard: 95000,
      vip: 125000,
      couple: 250000
    },
    serviceFeePerSeat: 5000
  };
}());
