"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useBookingStore } from "@/lib/stores/booking.store";
import type { Combo, Seat, Showtime } from "@/types/domain";

const seats: readonly Seat[] = Array.from({ length: 30 }, (_, index) => ({ id: `s-${index + 1}`, label: `${String.fromCharCode(65 + Math.floor(index / 10))}${(index % 10) + 1}`, kind: index % 9 === 0 ? "couple" : index % 4 === 0 ? "vip" : "standard", priceMultiplier: index % 9 === 0 ? 2 : index % 4 === 0 ? 1.5 : 1 }));
const combos: readonly Combo[] = [{ id: "classic", name: "Classic Duo", unitPrice: 89000 }, { id: "galaxy", name: "Galaxy Box", unitPrice: 129000 }];
export function ShowtimePicker({ showtimes }: { showtimes: readonly Showtime[] }) { const select = useBookingStore((s) => s.selectShowtime); const router = useRouter(); return <div className="grid gap-3">{showtimes.map((x) => <button key={x.id} className="rounded-lg border border-border p-4 text-left hover:border-primary" onClick={() => { select(x.id); router.push(`/booking/${x.id}/seats`); }}>{new Date(x.startsAt).toLocaleString("vi-VN")} · {x.format}</button>)}</div>; }
export function SeatPicker() { const selected = useBookingStore((s) => s.seatIds); const toggle = useBookingStore((s) => s.toggleSeat); const total = selected.reduce((sum, id) => sum + 90000 * (seats.find((x) => x.id === id)?.priceMultiplier ?? 1), 0); return <div className="grid gap-6"><div className="grid grid-cols-10 gap-2">{seats.map((seat) => <button key={seat.id} aria-pressed={selected.includes(seat.id)} disabled={seat.id === "s-7"} className={`aspect-square rounded text-xs ${selected.includes(seat.id) ? "bg-primary text-primary-foreground" : seat.id === "s-7" ? "bg-muted opacity-40" : seat.kind === "vip" ? "bg-cv-warning" : "bg-surface-raised"}`} onClick={() => toggle(seat.id)}>{seat.label}</button>)}</div><p>Ghế đã chọn: {selected.length} · {total.toLocaleString("vi-VN")}đ</p><Link className="rounded-lg bg-primary px-4 py-2 text-center text-primary-foreground" href="/booking/combos">Tiếp tục chọn combo</Link></div>; }
export function ComboPicker() { const quantities = useBookingStore((s) => s.comboQuantities); const set = useBookingStore((s) => s.setComboQuantity); return <div className="grid gap-4">{combos.map((combo) => <div key={combo.id} className="flex items-center justify-between rounded-lg border border-border p-4"><span>{combo.name} · {combo.unitPrice.toLocaleString("vi-VN")}đ</span><div className="flex gap-2"><button onClick={() => set(combo.id, (quantities[combo.id] ?? 0) - 1)}>−</button><span>{quantities[combo.id] ?? 0}</span><button onClick={() => set(combo.id, (quantities[combo.id] ?? 0) + 1)}>+</button></div></div>)}<Link className="rounded-lg bg-primary px-4 py-2 text-center text-primary-foreground" href="/booking/checkout">Thanh toán</Link></div>; }
export function Checkout() { const seats = useBookingStore((s) => s.seatIds); const issue = useBookingStore((s) => s.issueTicket); const router = useRouter(); if (!seats.length) return <p>Hãy chọn ít nhất một ghế trước khi thanh toán.</p>; return <button className="rounded-lg bg-primary px-4 py-2" onClick={() => { const ticket = { id: crypto.randomUUID(), code: `CV-${Date.now().toString().slice(-6)}`, movieTitle: "Minions & Monsters", showtimeId: "showtime-minions-d1-1800", seatLabels: seats, total: seats.length * 90000 }; issue(ticket); router.push(`/ticket/${ticket.id}`); }}>Thanh toán mock</button>; }
